# Generated by Django 3.0.8 on 2020-07-14 19:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('distrito', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adicional', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ValorCotizacion',
            fields=[
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cotizaciones.Cotizacion')),
                ('valor_subtotal', models.DecimalField(decimal_places=2, default=0.01, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_igv', models.DecimalField(decimal_places=2, default=0.01, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.01, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('unidad', models.CharField(choices=[('m2', 'metro cuadrado')], default='m2', max_length=20)),
                ('val_unit', models.DecimalField(decimal_places=2, default=0.01, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_item', models.DecimalField(decimal_places=2, default=0.01, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.Cotizacion')),
            ],
        ),
    ]
