# Generated by Django 3.0.8 on 2020-07-16 01:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorcotizacion',
            name='valor_igv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='valorcotizacion',
            name='valor_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='valorcotizacion',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
