# Generated by Django 3.0.8 on 2020-07-16 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_auto_20200716_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
